#cloud-config
package_update: true
packages:
  - docker.io
runcmd:
  - systemctl enable --now docker
  - docker run -d --name beacon --restart=always --network host -e DB_TARGET=${db_target} ${beacon_image}
